### ISSUE TITLE
Implémentation du MouseListener 

### ISSUE THREAD

**Issue by DrPyser** [DrPyser/Devoir2#3]
Ok, là c'est plus sérieux je pense. Faut décider de ce qu'on fait ensemble.

Le listener que j'écrit, il doit faire quelquechose. Il peut soit
- appeler et passer la carte cliquée à une méthode de PanneauDeCartes qui s'occupe de la retournée(en gèrant la limite de temps et tout),
- s'occuper lui même de retourner la carte cliquée, impliquant que le listener doit pouvoir gèrer la limite de temps sur l'affichage de la carte, impliquant que le listener doit avoir accès à à un compteur qui détermine le nombre de cartes cliqués depuis la fin du dernier "cycle", impliquant que la carte cliquée doit avoir cette information(puisque c'est le seul paramètre donné au listener), impliquant que la classe mère des cartes doit possèder ce compteur comme propriété statique.

la première option pose le problème que le listener n'a pas accès à une référence au panneau de carte, seulement à la carte cliquée(?).

**Comment by Adwind** [comment]
La classe PanneauDeCartes doit ensuite ajouter les cartes au panel et s'assurer de gérer les clicks souris sur les cartes et les délais d'affichage selon le déroulement du jeu précisé ci-dessous.(donc tu fait un truc dans le mien (je vais le copier coller ou linker ensemble) faut juste que sa return quelle est la carte toucher

Date: Fri, 20 Mar 2015 17:49:10 -0700

**Comment by DrPyser** [comment]
Les méthodes du listener ne peuvent pas retourner quoi que ce soit. Leur signature de retour est de type "void".

**Comment by Adwind** [comment]
@override

Date: Sun, 22 Mar 2015 09:57:27 -0700

**Comment by DrPyser** [comment]
je suis pas sûr de comprendre comment ça  marche. La carte cliquée envoit l'event au listener, alors comment est-ce que le panneau de carte peut catcher le return du listener?

**Comment by DrPyser** [comment]
C'est qui le caller de la méthode du listener? c'est fait automatiquement par la carte cliquée? Dans ce cas, seul la carte peut utiliser la valeur retournée par le listener...

**Comment by DrPyser** [comment]
Aussi, je suis pas sûr que simplement overidder la signature des méthodes du listener marche. Ces méthodes sont d'abord imposés par une interface que la classe "MouseAdapter" et ses sous-classe(notre listener) implémentent. Donc je pense pas qu'on puisse changer leur signature

**Comment by Adwind** [comment]
JButton quitButton = new JButton("Quit");

```
    quitButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent event) {
            System.exit(0);
        }
    });
```

Date: Sun, 22 Mar 2015 10:14:40 -0700

**Comment by DrPyser** [comment]
C'est quoi ça? À quoi ça me sert?
T'as pas changer la signature de la méthode... Et ça répond pas à ma question sur comment est-ce que le panneau de carte est supposé utiliser la valeur de retour du listener... Faudrait que je puisse appeler la méthode du panneau carte en lui passant en argument la carte. Ce que je peux pas faire vu que j'ai pas de référence au panneau de carte...

**Comment by Adwind** [comment]
sa sert a modifier une méthode déja implémenter ainsi tu peut return si besoin est des chose ou faire des action comme exit le system print qqch ou autre

Date: Sun, 22 Mar 2015 10:23:48 -0700

**Comment by DrPyser** [comment]
Je sais que je peux redéfinir les méthodes... Il faut que je  le fasse. Mais je suis pas convaincu que je peux changer la signature de la méthode, vu que cette dernière est imposée par l'interface que la classe implémente...

**Comment by DrPyser** [comment]
L'annotation "@override" est juste une sureté pour indiquer explicitement au compilateur que la méthode définie par après override une méthode parente, tel que si le nom de la méthode n'est pas celui d'une méthode parent(faute d'orthographe), le compilateur va se plaindre. Ça permet pas de faire quoi que ce soit de plus.

**Comment by DrPyser** [comment]
De ce que je comprend, y'a aucun moyen pour que le panneau de carte intercept le return du listener(s ic'est possible pour lui de retourner quelquechose). Seul le caller d'une fonction peut utiliser le resultat de cette dernière, et là le caller c'est le system, pas nos classes. C'est pour ça que sa signature est void. Le listener effectue des actions(comme appeler des méthodes d'autres classes auquelles il a accès), mais ne retourne rien.

**Comment by DrPyser** [comment]
Autres solutions:
- Donner au constructeur de la classe du Listener l'instance du panneau comme argument, ce qui lui permet d'accèder  aux méthodes du panneau.
